CREATE TABLE IF NOT EXISTS Users (
  UserID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  Username TEXT NOT NULL UNIQUE,
  Password TEXT NOT NULL,
  DateCreated INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Books (
    BookID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL UNIQUE,
    Author TEXT NOT NULL,
    ISBN TEXT NOT NULL,
    DatePublished INTEGER NOT NULL
);