PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
  UserID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  Username TEXT NOT NULL UNIQUE,
  Password TEXT NOT NULL,
  DateCreated INTEGER NOT NULL,
  UserType INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Authors (
    AuthorID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Locations (
    LocationID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Books (
    BookID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ISBN TEXT NOT NULL,
    Name TEXT NOT NULL,
    AuthorID INTEGER NOT NULL,
    DatePublished INTEGER NOT NULL,
    Genre INTEGER NOT NULL,

    FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID)
);

CREATE TABLE IF NOT EXISTS CopyOfBook (
    CopyID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    BookID INTEGER NOT NULL,
    OwnerID INTEGER NOT NULL,

    FOREIGN KEY (BookID) REFERENCES Books(BookID),
    FOREIGN KEY (OwnerID) REFERENCES Users(UserID)
);
